[supervisord]
nodaemon=true

[program:qdrant]
command=/qdrant/qdrant
directory=/qdrant
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:tei]
command=/usr/local/bin/text-embeddings-router --model-id BAAI/bge-small-en-v1.5 --port 80
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:bifrost]
command=/app/main -app-dir /app/data
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
